I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/test.rpy", line 6, in script
    init python:
  File "game/test.rpy", line 7, in <module>
    from os import getcwd, chdir, listdir, path, mkdir, isdir
ImportError: cannot import name 'isdir' from 'os' (C:\Users\jerem\OneDrive\Escritorio\renpy-8.1.3-sdk\lib\python3.9\os.pyc)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/test.rpy", line 6, in script
    init python:
  File "C:\Users\jerem\OneDrive\Escritorio\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jerem\OneDrive\Escritorio\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/test.rpy", line 7, in <module>
    from os import getcwd, chdir, listdir, path, mkdir, isdir
ImportError: cannot import name 'isdir' from 'os' (C:\Users\jerem\OneDrive\Escritorio\renpy-8.1.3-sdk\lib\python3.9\os.pyc)

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
tesr 1.0
Fri Mar 22 23:50:00 2024
