I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main.rpy", line 16, in script call
    $ list_to_start()
  File "game/mods/chapter_1_modder.rpy", line 48, in script
    
ScriptError: could not find label 'othera_'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/main.rpy", line 16, in script call
    $ list_to_start()
  File "game/mods/chapter_1_modder.rpy", line 48, in script
    
  File "C:\Users\jerem\OneDrive\Escritorio\rift_engine\ritf-engine\pro\tesr-1.0-win\tesr-1.0-win\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\jerem\OneDrive\Escritorio\rift_engine\ritf-engine\pro\tesr-1.0-win\tesr-1.0-win\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'othera_'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
tesr 1.0
Tue Apr 30 19:20:00 2024
